#!/usr/bin/env bash

set -euo pipefail

DRY_RUN=0
SUDO=0
SUDO_BIN=sudo
EXEC=""

log() {
    printf "[%s] %s\n" "$(date)" "$@"
}

usage() {
    echo "$0 [-d] [-s [-e sudo|doas]] [-P n] HOST"
    exit 1
}

while getopts dpse:P: arg; do
    case ${arg} in
        d) DRY_RUN=1 ;;
        s) SUDO=1 ;;
        e) SUDO_BIN="${OPTARG}" ;;
        p) ;; # for backwards-compatibility
        *) usage ;;
    esac
done
shift $((OPTIND - 1))


# Set the privilege escalation program.
if [ "$SUDO" -eq 1 ]
then
    EXEC="$SUDO_BIN"
fi

# Keep a persistent SSH connection open.
SSH_PARAMS=(-q -o "ControlMaster=auto" -o "ControlPath=/tmp/drist_ssh_%h_%p_%r.sock" -o "ControlPersist=1m")

cleanup() {
    log "Closing persistent SSH connection..."
    ssh "${SSH_PARAMS[@]}" -O exit -N "$HOST"
}

trap cleanup EXIT


# Require the HOST parameter.
if [ "$#" -ne 1 ]; then
    usage
else
    HOST="$1"
    # shellcheck disable=SC2029
    if ! read -r HOSTNAME; then
        echo "error: could not fetch hostname"
        exit 2
    fi < <(ssh "${SSH_PARAMS[@]}" "$HOST" "$EXEC uname -n")
fi


copy_files() {
    SRC="$1"
    DST="$2"

    if [ -d "$SRC" ]; then
        LIST=$(mktemp /tmp/drist-rsync.XXXXXXXXXX)
        if [ -f "$LIST" ]; then
            log "Copying files from $SRC..."
            find "$SRC" -type f | cut -d '/' -f 2- | tee "$LIST" | sed 's/^/  \//'

            if [ "$DRY_RUN" -ne 1 ]; then
                # -l = keep symlink / -D = special device
                rsync -e "ssh ${SSH_PARAMS[*]}" --rsync-path="$EXEC rsync" -lD --files-from="$LIST" "$SRC/" "$DST":/
            fi
            rm "$LIST"
        fi
    fi
}


remote_script() {
    SRC="$1"
    DST="$2"

    if [ -f "$SRC" ]; then
        log "Executing $SRC..."

        if [ "$DRY_RUN" -ne 1 ]; then
            # shellcheck disable=SC2029 disable=SC2087
            ssh "${SSH_PARAMS[@]}" "$DST" "DRIST=$(mktemp /tmp/drist.XXXXXXXXXXXX) && cat - > \$DRIST && chmod u+x \$DRIST && $EXEC \$DRIST ; rm \$DRIST" < "$SRC"
        fi
    fi
}


delete_files() {
    SRC="$1"
    DST="$2"

    if [ -d "$SRC" ]; then
        LIST=$(mktemp /tmp/drist-rsync.XXXXXXXXXX)
        if [ -f "$LIST" ]; then
            log "Removing files from $SRC..."
            find "$SRC" -type f | sed 's/"/\\&/' | \
                awk -v path="$SRC" '{ printf "\"%s\" ",substr($0,length(path)+1) }' | \
                tee "$LIST" | sed 's/^/  /'

            if [ "$DRY_RUN" -ne 1 ]; then
                # shellcheck disable=SC2029
                test -s "$LIST" && ssh "${SSH_PARAMS[@]}" "$DST" "$EXEC rm -f $(cat "$LIST")"
            fi
            rm "$LIST"
        fi
    fi
}

copy_files "files" "$HOST"
copy_files "files-$HOSTNAME" "$HOST"
remote_script "script" "$HOST"
remote_script "script-$HOSTNAME" "$HOST"
delete_files "absent" "$HOST"
delete_files "absent-$HOSTNAME" "$HOST"
